apiVersion: v1
kind: Pod
metadata:
  name: broken-Pod
  labels:
    app: webserver
spec:
  containers:
  - name: broken-container
    image: nonexistent-image:latest
    ports:
    - containerPort: 8080