apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
  - name: container-one
    image: nginx:1.25
    ports:
    - containerPort: 80
  - name: apache
    image: httpd:2.4
    ports:
    - containerPort: 8080
    command:
      - sh
      - -c
      - |
        sed -i 's/Listen 80/Listen 8080/' /usr/local/apache2/conf/httpd.conf && \
        apachectl -D FOREGROUND
  - name: busybox
    image: busybox
    command: ["sh", '-c', 'while true; do sleep 3600; done']