apiVersion: v1
kind: Pod
metadata:
  name: network-test-pod
spec:
  containers:
  
  # Main container - nginx
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
  
  # Sidecar container - curl (to test connectivity)
  - name: sidecar-tester
    image: curlimages/curl:latest
    command: ['sh', '-c', 'sleep 3600']