apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
  - name: container-one
    image: nginx:1.25
    ports:
    - containerPort: 80
  - name: busybox
    image: busybox
    command: ["sh", '-c', 'while true; do sleep 3600; done']