networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge
  database_net:
    driver: bridge
  monitoring_net:
    driver: bridge

servcies:
  postgres:
    image: postgres:13-alpine
    networks:
      - database_net
    environment:
      POSTGRES_USER: puser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - .init-db:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U puser -d pdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  redis:
    image: redis:6-alpine
    networks:
      - database_net
    volumes:
      - redisdata:/data

    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  pgdata:
  redisdata:

# port mapping is not required as services communicates over internal docker networks example frontend_net, 
# backend_net, database_net, backend:5443 liek this it connect, for external access port mapping can be done.