global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Monitor Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']

  # We'll add more targets later!